services:
  nginx-proxy:
    image: nginx:alpine
    container_name: chatroom-nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - frontend
      - backend

  frontend:
    image: chatroom-frontend
    build:
      context: .
      dockerfile: .docker/dockerfile.frontend

  backend:
    image: chatroom-backend
    build:
      context: .
      dockerfile: .docker/dockerfile.backend
    environment:
      - PORT=80