services:
  backend:
    container_name: chat-backend
    build: backend
    ports:
      - "3000:80"
  frontend:
    image: nginx:latest
    container_name: chat-frontend
    ports:
      - "8080:80"
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"